# Generated by Django 5.0.3 on 2025-01-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_img_post_pc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pc',
            new_name='img',
        ),
    ]
