# Generated by Django 5.0.3 on 2025-01-07 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_pc_post_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=8, null=True)),
                ('kyc_document', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('kyc_document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='pan_cards/')),
                ('bank_passbook', models.FileField(blank=True, null=True, upload_to='bank_passbooks/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
